# Generated by Django 4.2.8 on 2023-12-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_userwallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
